AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template sets up all resources for the lambda notification system 

# Parameters:
  # InStrideServicesAccountID:
  #   Type: String
  #   Default: '{{resolve:ssm:InStrideServicesAccountID:1}}'
  #   Description: 12-digit AWS account ID

  # UvaAcademicPartnerId:
  #   Type: String
  #   Default: '785983a4-dfa0-4d57-bc54-7af4f8a89f47'
  #   Description: Academic Partner ID of UVA

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs12.x

Resources:
  # -----START OF DELTA LAKE CONFIGURATIONS-----

  NotificationsConfigBucket:
    Type: AWS::S3::Bucket
    # DeletionPolicy: Retain
    Properties:
      BucketName: !Sub '${AWS::StackName}--notification-config'

  # libs:
  #   Type: AWS::Lambda::LayerVersion
  #   Properties:
  #     LayerName: !Sub '${AWS::StackName}--layer'
  #     Description: Dependencies for the notification app.
  #     Content:
  #       S3Bucket: !Sub '${AWS::StackName}--notification-config'
  #       S3Key: layer.zip
  #     CompatibleRuntimes:
  #       - nodejs12.x    

  NotificationFromLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      FunctionName: !Sub '${AWS::StackName}--notification-from-log'
      Handler: index.LambdaNotifierHandler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: '*'
      # Layers:
      #   - !Ref libs

  UpdateTriggersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build
      FunctionName: !Sub '${AWS::StackName}--update-triggers'
      Handler: index.LambdaUpdatedHandler
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:*
              Resource: '*'
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:*
              Resource: '*'
      Events:
        S3ConfigChangeTrigger:
          
          Type: S3
          Properties:
            Bucket: !Ref NotificationsConfigBucket
            Events: 
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*
      # Layers:
      #   - !Ref libs

