AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template sets up all resources for the lambda notification system
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs12.x
Resources:
  NotificationsConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}--notification-config
  NotificationFromLogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://cf--notification-system--testing/eb5e0da7cebd4ca817e2a2b27a34abdf
      FunctionName:
        Fn::Sub: ${AWS::StackName}--notification-from-log
      Handler: index.LambdaNotifierHandler
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - s3:*
          Resource: '*'
