AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This template sets up all resources for the lambda notification system
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs14.x
Resources:
  NotificationsConfigBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${AWS::StackName}-notification-config
