export enum EnvVariables {
    NOTIFICATION_CONFIG_BUCKET_NAME = 'NOTIFICATION_CONFIG_BUCKET_NAME',
    AWS_REGION = 'AWS_REGION',
    AWS_ACCOUNT_ID = 'AWS_ACCOUNT_ID',
    LAMBDA_NOTIFIER_NAME = 'LAMBDA_NOTIFIER_NAME',
    NOTIFICATION_LAMBDA_ARN = 'NOTIFICATION_LAMBDA_ARN',
    DEFAULT_SNS_ARN = 'DEFAULT_SNS_ARN',
    RECIPIENTS_CONFIG_BUCKET_NAME = 'RECIPIENTS_CONFIG_BUCKET_NAME',
    BACKUP_CONFIG_NAME = 'BACKUP_CONFIG_NAME'
}