export const EnvVariables = {
    KMS_KEY_ID_TS: 'KMS_KEY_ID_TS',
    NOTIFICATION_CONFIG_BUCKET_NAME: 'NOTIFICATION_CONFIG_BUCKET_NAME',
    AWS_REGION: 'AWS_REGION',
    AWS_ACCOUNT_ID: 'AWS_ACCOUNT_ID',
    LAMBDA_NOTIFIER_NAME: 'LAMBDA_NOTIFIER_NAME',
    NOTIFICATION_LAMBDA_ARN: 'NOTIFICATION_LAMBDA_ARN'
}